{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.libxposed",
    "module": "api",
    "version": "100",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-100.aar",
          "url": "api-100.aar",
          "size": 16211,
          "sha512": "849376309cabb2265a3dfa722d544e9f052f42346a6a1744e1e1e323d53f6473a4c96fabf481f0189963526b9e87bbbf0b68740e6c9a83bbdb2fe853084ba1bb",
          "sha256": "7a784d642b21b0fd4e2b5053c0c38339101b52e01e197e4e50d59f97162b3666",
          "sha1": "349998705b85492d5d89ddae58a53bb06a7ef2bc",
          "md5": "6b1bcf89519feb91b318dbf6cd76b53f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-100.aar",
          "url": "api-100.aar",
          "size": 16211,
          "sha512": "849376309cabb2265a3dfa722d544e9f052f42346a6a1744e1e1e323d53f6473a4c96fabf481f0189963526b9e87bbbf0b68740e6c9a83bbdb2fe853084ba1bb",
          "sha256": "7a784d642b21b0fd4e2b5053c0c38339101b52e01e197e4e50d59f97162b3666",
          "sha1": "349998705b85492d5d89ddae58a53bb06a7ef2bc",
          "md5": "6b1bcf89519feb91b318dbf6cd76b53f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-100-sources.jar",
          "url": "api-100-sources.jar",
          "size": 10244,
          "sha512": "4823fb19b83fab2fcf6de7b9357b3da7407015ec45b7783eb49fab52614c98d327145de3bc4357b6345b82dbe3a622855c0602096ee431636d8ce199f79db5e9",
          "sha256": "725334825579012d8dc678bcfca49e1923ada14a7744e3595e74a8efe8261a65",
          "sha1": "7c41e80d64aed490440c30bb660ab9867c003540",
          "md5": "3674e59f9a64606c70d1ec03235f663c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-100-javadoc.jar",
          "url": "api-100-javadoc.jar",
          "size": 395383,
          "sha512": "74da0cbf45e3f2799fb00fec5068ff9f46b71a8d923026d14f97815e32b06cd4132fae6a4ada2fdb66bc2ff1460f0ca267d1a834c6382bd951e90b30c60bda7d",
          "sha256": "86e25c8d5b597f1f22215334f127fdb3f5c3d82c568c6abe55638ab502218b09",
          "sha1": "9576e6e778bfd40113323a2dbebf24c24c6070a9",
          "md5": "9884380018a7c165555d816b49ab6002"
        }
      ]
    }
  ]
}
